-- MySQL Script generated by MySQL Workbench
-- Wed Jul 15 16:26:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `FIO` VARCHAR(200) NOT NULL,
  `address` TINYTEXT NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `id_Client_UNIQUE` (`id_client` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Car_rent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Car_rent` (
  `id_car` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(100) NOT NULL,
  `cost` INT NOT NULL,
  `type` TINYTEXT NULL,
  PRIMARY KEY (`id_car`),
  UNIQUE INDEX `id_car_UNIQUE` (`id_car` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`History` (
  `id_history` INT NOT NULL AUTO_INCREMENT,
  `id_client` INT NOT NULL,
  `id_car` INT NOT NULL,
  `date_issue` DATETIME NOT NULL,
  `date_return` DATETIME NULL,
  PRIMARY KEY (`id_history`),
  UNIQUE INDEX `id_history_UNIQUE` (`id_history` ASC),
  INDEX `id_client_idx` (`id_client` ASC),
  INDEX `id_car_idx` (`id_car` ASC),
  CONSTRAINT `id_client`
    FOREIGN KEY (`id_client`)
    REFERENCES `mydb`.`Clients` (`id_client`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_car`
    FOREIGN KEY (`id_car`)
    REFERENCES `mydb`.`Car_rent` (`id_car`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
